adaptation:
  init_mode: sev_enc_with_corr
  corr_mult: 1.2
  sev_enc_model_class: flash_diffusion.severity_encoder.LDMSevEncoder
  sev_enc_ckpt_path: 'checkpoints/sevenc_random_inpaint_lsun_bedroom.ckpt'
baseline:
  class: 'samplers.latent_recon.PSLD'
  ldm_ckpt_path: 'ldm/models/ldm/lsun_beds256/model.ckpt'
  data_consistency:
    dc_step: 10.0
    ae_weight: 0.05
data:
    dataset: 'lsun_bedroom'
    split: 'test'
    num_images: 200
    fixed_severity: -1
    t_range:
      - 0.875
      - 1.0
    degradation_config: 'flash_configs/inverse_configs/inpainting_fixed_noise.yaml'